CONFIG_LLVM_USE_LLD=y
CONFIG_COMPILER_RT_RTLIB=y

CONFIG_MAIN_STACK_SIZE=16384

CONFIG_FPU=y
CONFIG_FPU_SHARING=y

#CONFIG_SPEED_OPTIMIZATIONS=n # -O2
#CONFIG_SIZE_OPTIMIZATIONS=n # -Os

#CONFIG_COMPILER_OPT="-Oz -mno-outline"
CONFIG_COMPILER_OPT="-O2"
